/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;


import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.io.OWLXMLOntologyFormat;
import org.semanticweb.owlapi.io.RDFXMLOntologyFormat;
import org.semanticweb.owlapi.model.AddAxiom;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLAxiom;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLClassAssertionAxiom;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLDeclarationAxiom;
import org.semanticweb.owlapi.model.OWLIndividual;
import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLObjectProperty;
import org.semanticweb.owlapi.model.OWLObjectPropertyAssertionAxiom;
import org.semanticweb.owlapi.model.OWLOntology;
import org.semanticweb.owlapi.model.OWLOntologyCreationException;
import org.semanticweb.owlapi.model.OWLOntologyManager;
import org.semanticweb.owlapi.model.OWLOntologyStorageException;
import org.semanticweb.owlapi.model.PrefixManager;
import org.semanticweb.owlapi.util.DefaultPrefixManager;

/**
 *
 * @author Bisma
 */
public class insertauthor extends javax.swing.JFrame {

    /**
     * Creates new form insertauthor
     */
    public insertauthor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(742, 478));
        setMinimumSize(new java.awt.Dimension(742, 478));
        setPreferredSize(new java.awt.Dimension(742, 478));
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Khmer UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("NOVEL MANIA");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 750, 70);

        jLabel2.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jLabel2.setText("Enter Author Name:");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 100, 140, 50);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(230, 110, 350, 40);

        jLabel4.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jLabel4.setText("Enter Author Discription:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 190, 170, 40);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(230, 200, 350, 140);

        jButton1.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jButton1.setText("INSERT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(180, 390, 230, 50);

        jButton3.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jButton3.setText("BACK");
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(430, 390, 210, 50);

        jLabel1.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bisma\\Documents\\NetBeansProjects\\OntologyNovel\\images\\7.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 750, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents
   private static Object ProtegeOWL;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     Insertion s=new Insertion();
        s.setVisible(true);
      insertauthor.this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String discription= jTextArea1.getText();
       String nameofauthor= jTextField1.getText();
       
       if(discription.equals("") || nameofauthor == "" )
       {
           JOptionPane.showMessageDialog(null, "Enter all fields");
       }
       else {
        
           try {
               nameofauthor= nameofauthor.replaceAll("\\s+","_");
               IRI ontologyIRI = IRI.create("http://www.semanticweb.org/bisma/ontologies/2016/2/noveljkp.owl");
               OWLOntologyManager man = OWLManager.createOWLOntologyManager();
               OWLOntology ontology = man.loadOntologyFromOntologyDocument(new File("jkp.owl"));
               OWLDataFactory factory = man.getOWLDataFactory();
               PrefixManager pm = new DefaultPrefixManager(ontologyIRI+"#");
OWLClass person = factory.getOWLClass(":Author", pm);
OWLClass woman = factory.getOWLClass(IRI.create(ontologyIRI + "#Name"));
           man.addAxiom(ontology, factory.getOWLSubClassOfAxiom(woman, person));
               OWLNamedIndividual authorname = factory.getOWLNamedIndividual(":"+nameofauthor, pm);
//insert with adding type:
               OWLClassAssertionAxiom classAssertion = factory.getOWLClassAssertionAxiom(woman, authorname);
               man.addAxiom(ontology, classAssertion);
              OWLObjectProperty isa = factory.getOWLObjectProperty(IRI
                       .create(ontologyIRI + "#isa"));
               OWLIndividual author = factory.getOWLNamedIndividual(IRI
            .create(ontologyIRI + "#Author"));
               OWLObjectPropertyAssertionAxiom axiom1 = factory
                       .getOWLObjectPropertyAssertionAxiom(isa, authorname, author);
               AddAxiom addAxiom1 = new AddAxiom(ontology, axiom1);
               man.applyChange(addAxiom1);
               OWLDataProperty author_name = factory.getOWLDataProperty(IRI.create(ontologyIRI + "#author_name"));
                OWLDataProperty author_detail = factory.getOWLDataProperty(IRI.create(ontologyIRI + "#author_detail"));
               // We create a data property assertion
               OWLAxiom axiom4 = factory.getOWLDataPropertyAssertionAxiom(author_name,authorname ,nameofauthor );
               man.applyChange(new AddAxiom(ontology, axiom4));
                OWLAxiom axiom5 = factory.getOWLDataPropertyAssertionAxiom(author_detail,authorname ,discription);
               man.applyChange(new AddAxiom(ontology, axiom5));
               man.saveOntology(ontology, new RDFXMLOntologyFormat());
               jTextArea1.setText("");
       jTextField1.setText("");
           } catch (OWLOntologyCreationException ex) {
               Logger.getLogger(insertauthor.class.getName()).log(Level.SEVERE, null, ex);
           } catch (OWLOntologyStorageException ex) {
               Logger.getLogger(insertauthor.class.getName()).log(Level.SEVERE, null, ex);
           }
   
       }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(insertauthor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(insertauthor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(insertauthor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(insertauthor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new insertauthor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
