/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import static com.fasterxml.jackson.databind.jsonFormatVisitors.JsonFormatTypes.NULL;
import static javafx.beans.binding.Bindings.or;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import org.apache.jena.ontology.OntModel;
import org.apache.jena.ontology.OntModelSpec;
import org.apache.jena.query.Query;
import org.apache.jena.query.QueryExecution;
import org.apache.jena.query.QueryExecutionFactory;
import org.apache.jena.query.QueryFactory;
import org.apache.jena.query.ResultSetFormatter;
import org.apache.jena.rdf.model.ModelFactory;
import org.apache.jena.util.FileManager;

/**
 *
 * @author Bisma
 */
public class NovelDetail extends javax.swing.JFrame {
String NovelName;
    /**
     * Creates new form NovelDetail
     */
    public NovelDetail() {
        initComponents();
        
    }
   
    public NovelDetail(String Name) {
       
        NovelName=Name;
        initComponents();
        detailer();
    }
  void detailer()
    {
        NovelName=NovelName.replaceAll("\\s+","");
    OntModel model = ModelFactory.createOntologyModel(OntModelSpec.OWL_MEM_MICRO_RULE_INF);
FileManager.get().readModel( model, "jkp.owl" );
       String queryString ="prefix my: <http://www.semanticweb.org/bisma/ontologies/2016/2/noveljkp.owl#> \n" +
"PREFIX owl:     <http://www.w3.org/2002/07/owl#>\n" +
"SELECT ?p ?o  \n" +
"WHERE {  my:"+NovelName+" ?p ?o . filter isLiteral(?o) }";
Query query = QueryFactory.create(queryString);
QueryExecution qe= QueryExecutionFactory.create(query, model);
org.apache.jena.query.ResultSet resultset = qe.execSelect();
java.io.ByteArrayOutputStream baos= new java.io.ByteArrayOutputStream();
            ResultSetFormatter.outputAsCSV(baos, resultset);
            String answer= baos.toString();
                      answer= java.util.Arrays.toString(answer.split("http://www.semanticweb.org/bisma/ontologies/2016/2/noveljkp.owl#author_detail,"));
 String a="[p,o\n" +
"http://www.semanticweb.org/bisma/ontologies/2016/2/noveljkp.owl#noveldetail,\"";
 int b=a.length();
    answer = answer.substring(b, answer.length());
    int c=answer.length()-b;
    int d=c/2;
    String s=answer.substring(0, d);
     jLabel6.setText("<html><p>"+s+"</p></html>");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(850, 650));
        setMinimumSize(new java.awt.Dimension(850, 650));
        setPreferredSize(new java.awt.Dimension(850, 650));
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Khmer UI", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("NOVEL MANIA");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 10, 830, 50);

        jComboBox1.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Characters", "Places" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(450, 230, 120, 40);

        jLabel5.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SEARCH:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(380, 230, 60, 40);

        jButton1.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(570, 500, 110, 30);

        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(370, 280, 310, 210);

        jButton2.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jButton2.setText("SEARCH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(580, 230, 100, 40);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 60, 810, 120);

        jButton3.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jButton3.setText("SEARCH WITH NAME");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(370, 500, 190, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/6.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 140, 820, 540);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/9.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(4, -6, 840, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents
 javax.swing.DefaultListModel listModel = new javax.swing.DefaultListModel();
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         NovelName=NovelName.replaceAll("\\s+","");
         
          if (!listModel.isEmpty()) {  listModel.removeAllElements();
          }  
        String chckitem=jComboBox1.getSelectedItem().toString();
        if("Characters".equals(chckitem))
        {
        OntModel model = ModelFactory.createOntologyModel(OntModelSpec.OWL_MEM_MICRO_RULE_INF);
        FileManager.get().readModel( model, "jkp.owl" );
        String queryString ="prefix uni: <http://www.semanticweb.org/bisma/ontologies/2016/2/noveljkp.owl#> \n" +
        "select * {?Person uni:belongsto uni:"+NovelName+"}";
        listModel.addElement("Character");
        Query query = QueryFactory.create(queryString);
        QueryExecution qe= QueryExecutionFactory.create(query, model);
        org.apache.jena.query.ResultSet resultset = qe.execSelect();
        java.io.ByteArrayOutputStream baos= new java.io.ByteArrayOutputStream();
        ResultSetFormatter.outputAsCSV(baos, resultset);
        String answer= baos.toString();
        answer= java.util.Arrays.toString(answer.split("http://www.semanticweb.org/bisma/ontologies/2016/2/noveljkp.owl#"));
        String[]  array = answer.split(",");
        String lastOne = array[array.length-1];
        lastOne=lastOne.substring(0,lastOne.length()-1);
       for(int i=1;i<array.length-1;i++)
       {
        listModel.addElement(array[i]);
       }
                        listModel.addElement(lastOne);
        
        
        }
         if("Places".equals(chckitem))
        {
        OntModel model = ModelFactory.createOntologyModel(OntModelSpec.OWL_MEM_MICRO_RULE_INF);
        FileManager.get().readModel( model, "jkp.owl" );
        String queryString ="prefix uni: <http://www.semanticweb.org/bisma/ontologies/2016/2/noveljkp.owl#> \n" +
"select * {?Place uni:isaplaceof uni:"+NovelName+"}";
        System.out.println(queryString);
        listModel.addElement("Places");
        Query query = QueryFactory.create(queryString);
        QueryExecution qe= QueryExecutionFactory.create(query, model);
        org.apache.jena.query.ResultSet resultset = qe.execSelect();
        java.io.ByteArrayOutputStream baos= new java.io.ByteArrayOutputStream();
        ResultSetFormatter.outputAsCSV(baos, resultset);
        String answer= baos.toString();
        answer= java.util.Arrays.toString(answer.split("http://www.semanticweb.org/bisma/ontologies/2016/2/noveljkp.owl#"));
        String[]  array = answer.split(",");
        String lastOne = array[array.length-1];
        lastOne=lastOne.substring(0,lastOne.length()-1);
       for(int i=1;i<array.length-1;i++)
       {
        listModel.addElement(array[i]);
       }
                        listModel.addElement(lastOne);
        
        
        }
         
           jList1.setModel(listModel);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         user s= new  user();
      s.setVisible(true);
      NovelDetail.this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    String selectedIndex =  (String) jList1.getSelectedValue();
    if("null".equals(selectedIndex) || "Characters".equals(selectedIndex) || "Availability".equals(selectedIndex) || "Places".equals(selectedIndex))
    JOptionPane.showMessageDialog(null, "SELECT NAME");
     else
    {
        Detail s= new  Detail(selectedIndex);
      s.setVisible(true);
      NovelDetail.this.setVisible(false);
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovelDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovelDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovelDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovelDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovelDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
